import type { Metadata } from "next";
import "./globals.css";
import TopNav from "./components/navbar/TopNav";
import Providers from "./components/Providers";


export const metadata: Metadata = {
  title: "PeKava",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <TopNav></TopNav>
        <Providers>{children}</Providers> 
      </body>
    </html>
  );
}
