import type { Metadata } from "next";
import "./globals.css";
import TopNav from "./components/navbar/TopNav";
import Providers from "./components/Providers";
import { auth } from "@/auth";


export const metadata: Metadata = {
  title: "PeKava",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const userId = session?.user?.id || null;
  const profileComplete = session?.user?.profileComplete || false;

  return (
    <html lang="en">
      <body>
        <TopNav></TopNav>
        <Providers profileComplete={profileComplete} userId={userId}>{children}</Providers> 
      </body>
    </html>
  );
}
